# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-28 14:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uwkm_streamfields', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='streamfieldssettings',
            name='google_api_key',
            field=models.CharField(blank=True, help_text='API Key van Google', max_length=255),
        ),
    ]
